appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: oCFOdKF6ADygoY3nJstiZFufBd1VrSfnm1d5bVvICLSgNOR+5Fl3FK4bacFtofKijDdwPjSyfsvekaMgaA+dcYi4pIntdIOv4TCZ+nowBPuJCiXjn77CZ+Dis7AM5lwe4cH0L4u0u3674KxQSpcYAI6GaipiEHYnv82DoKH4by7h0a0jv+PRoRfWgPurjhqxUqsKEF4bUYWNiNXWPOlKgMhfNfwqADQuQPY3wFQyk9/p27COX1O5oBcQRr4pKFw0KKzB2hEsrg49nWmaLCS9DBlOoqMVFWaFG0P33h7+2dn3+I1W6kwELVcU69jCZUXyEJlM2i/1e7OvLEvnYcxhvY13bAeiX/k7oR3AwQi9ekXH+gifkPFSd/+PrUHuewRzHDYlQDYcj0Om/lPiQ2rSUk+42E0BTRKbb3CNTtXtpyjegEmXfNoX/feokhni0WnOfhV/MgaZa0dWNY9GerVGjywGZRzOVLCg8vJMmvw+V6JakQFUWPpAy6Je0ieEzPT/E/GCwtINeZk0Fysf2gcgP5xXHm0d+LJG6it69I1E5J3c/4q7avKr7oyaLBd55JH2lh86MxA0D6xFoj+puaQX9HDKnt0gn4wrfl77YTPBOLih0/lmnGpE/GieaGJaIegAFu2OlEmOukloeFnm3ico3fyiVPXioPj00ZGOxEAlMZQ=}
provider:
  win: azure
conda_forge_output_validation: true
